#!/usr/bin/env python3
"""Stdlib unit checks for cookie_jar.py (#615). Run: python3 tests/test_cookie_jar.py"""
import importlib.util, os, tempfile, time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
spec = importlib.util.spec_from_file_location(
    "cookie_jar", os.path.join(ROOT, "src", "scripts", "cookie_jar.py"))
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)

# The anonymous jar from the 2026-09-19 incident: three cookies, no login.
ANON_JAR = ("# Netscape HTTP Cookie File\n"
            ".youtube.com\tTRUE\t/\tTRUE\t0\t__Secure-YNID\tv\n"
            ".youtube.com\tTRUE\t/\tFALSE\t0\tPREF\tf6=40000000\n"
            ".youtube.com\tTRUE\t/\tTRUE\t0\tSOCS\tCAI\n")
LOGGED_IN_JAR = ANON_JAR + ".youtube.com\tTRUE\t/\tTRUE\t0\tLOGIN_INFO\tAFm\n"


def _jar(d, text):
    p = os.path.join(d, "yt-cookies.txt")
    with open(p, "w", encoding="utf-8") as fh:
        fh.write(text)
    return p


def t_text_has_login_needs_a_marker():
    assert m.text_has_login(ANON_JAR) is False
    assert m.text_has_login(LOGGED_IN_JAR) is True
    for marker in m.COOKIE_MARKERS:
        assert m.text_has_login(f".youtube.com\tTRUE\t/\tTRUE\t0\t{marker}\tv\n"), marker
    assert m.text_has_login("") is False and m.text_has_login(None) is False


def t_jar_has_login_reads_the_file():
    with tempfile.TemporaryDirectory() as d:
        assert m.jar_has_login(_jar(d, ANON_JAR)) is False
        assert m.jar_has_login(_jar(d, LOGGED_IN_JAR)) is True


def t_jar_has_login_is_unknown_without_a_jar():
    # No jar is "unknown", not "logged out": the relay must not blame a login it
    # never had a file for.
    assert m.jar_has_login(None) is None
    assert m.jar_has_login("") is None
    with tempfile.TemporaryDirectory() as d:
        assert m.jar_has_login(os.path.join(d, "nope.txt")) is None
        assert m.jar_has_login(d) is None            # a directory: unreadable as a jar


def t_hint_names_the_command():
    assert "racecast cookies <browser>" in m.LOGGED_OUT_HINT


# A browser export as yt-dlp writes it (#616): the whole profile, not one site.
BROWSER_JAR = ("# Netscape HTTP Cookie File\n"
               "# This file is generated by yt-dlp.  Do not edit.\n"
               "\n"
               ".youtube.com\tTRUE\t/\tTRUE\t0\tSAPISID\tyt\n"
               "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t0\tLOGIN_INFO\tyt\n"
               "www.youtube.com\tFALSE\t/\tTRUE\t0\tVISITOR\tyt\n"
               ".google.com\tTRUE\t/\tTRUE\t0\tSID\tgoogle\n"
               "#HttpOnly_accounts.google.com\tFALSE\t/\tTRUE\t0\tLSID\tgoogle\n"
               ".github.com\tTRUE\t/\tTRUE\t0\tlogged_in\tgithub\n"
               ".twitch.tv\tTRUE\t/\tTRUE\t0\tauth-token\ttwitch\n"
               "id.twitch.tv\tFALSE\t/\tTRUE\t0\tlogin\ttwitch\n"
               ".notyoutube.com\tTRUE\t/\tTRUE\t0\tlook\talike\n"
               "youtube.com.evil.example\tFALSE\t/\tTRUE\t0\tlook\talike\n"
               "broken line without tabs\n")


def _names(text):
    return sorted(line.split("\t")[5] for line in text.splitlines()
                  if line.count("\t") == 6)


def t_filter_keeps_only_youtube_cookies():
    kept, dropped = m.filter_jar_text(BROWSER_JAR, "youtube")
    # .google.com is left out on purpose: requests to youtube.com never carry it,
    # and a live resolve with the youtube.com cookies alone was measured to work.
    assert _names(kept) == ["LOGIN_INFO", "SAPISID", "VISITOR"], _names(kept)
    assert dropped == 8, dropped
    assert kept.startswith("# Netscape HTTP Cookie File\n# This file is generated")
    assert m.text_has_login(kept) is True


def t_filter_keeps_only_twitch_cookies():
    kept, dropped = m.filter_jar_text(BROWSER_JAR, "twitch")
    assert _names(kept) == ["auth-token", "login"], _names(kept)
    assert dropped == 9, dropped


def t_filter_drops_lookalike_domains():
    kept, _ = m.filter_jar_text(BROWSER_JAR, "youtube")
    assert "alike" not in kept and "evil" not in kept and "github" not in kept
    assert "broken line" not in kept


def t_filter_rejects_an_unknown_platform():
    try:
        m.filter_jar_text(BROWSER_JAR, "vimeo")
    except ValueError as exc:
        assert "vimeo" in str(exc)
    else:
        raise AssertionError("an unknown platform must not keep everything")


def t_filter_jar_rewrites_the_file_owner_only():
    with tempfile.TemporaryDirectory() as d:
        p = _jar(d, BROWSER_JAR)
        assert m.filter_jar(p, "youtube") == 8
        with open(p, encoding="utf-8") as fh:
            assert _names(fh.read()) == ["LOGIN_INFO", "SAPISID", "VISITOR"]
        if os.name == "posix":
            assert os.stat(p).st_mode & 0o777 == 0o600, oct(os.stat(p).st_mode)
        assert os.listdir(d) == ["yt-cookies.txt"], os.listdir(d)   # no temp file left
        assert m.filter_jar(p, "youtube") == 0                      # idempotent


def t_filter_jar_is_none_without_a_jar():
    with tempfile.TemporaryDirectory() as d:
        assert m.filter_jar(os.path.join(d, "nope.txt"), "youtube") is None
        assert m.filter_jar(None, "youtube") is None



def t_filter_splits_lines_like_yt_dlp():
    # A foreign cookie value carrying U+2028 plus six tabs must not become a
    # youtube.com line: yt-dlp reads that whole line as one 13-field entry (#616).
    for brk in ("\u2028", "\u2029", "\x85", "\x0b", "\x0c", "\x1c"):
        jar = f"evil.com\tTRUE\t/\tTRUE\t0\tx\ta{brk}.youtube.com\tTRUE\t/\tTRUE\t0\tSID\tattacker\n"
        kept, dropped = m.filter_jar_text(jar, "youtube")
        assert "attacker" not in kept and dropped == 1, (repr(brk), kept, dropped)


def t_filter_drops_a_platform_cookie_with_a_control_character():
    for ch in ("\u2028", "\x85", "\x00", "\x1f", "\r"):
        line = f".youtube.com\tTRUE\t/\tTRUE\t0\tSID\ta{ch}b\n"
        assert m.filter_jar_text(line, "youtube") == ("", 1), repr(ch)


def t_filter_jar_keeps_the_bytes_of_a_kept_cookie():
    raw = b".youtube.com\tTRUE\t/\tTRUE\t0\tPREF\tv\xff1\n.github.com\tTRUE\t/\tTRUE\t0\tx\ty\n"
    with tempfile.TemporaryDirectory() as d:
        p = os.path.join(d, "yt-cookies.txt")
        with open(p, "wb") as fh:
            fh.write(raw)
        assert m.filter_jar(p, "youtube") == 1
        with open(p, "rb") as fh:
            assert fh.read() == b".youtube.com\tTRUE\t/\tTRUE\t0\tPREF\tv\xff1\n"


def t_filter_jar_writes_to_dest():
    with tempfile.TemporaryDirectory() as d:
        raw = os.path.join(d, "raw.txt")
        with open(raw, "w", encoding="utf-8") as fh:
            fh.write(BROWSER_JAR)
        out = os.path.join(d, "yt-cookies.txt")
        assert m.filter_jar(raw, "youtube", dest=out) == 8
        with open(out, encoding="utf-8") as fh:
            assert _names(fh.read()) == ["LOGIN_INFO", "SAPISID", "VISITOR"]


def _failing(exc_type):
    def fail(*args, **kwargs):
        raise exc_type("simulated failure")
    return fail


def t_filter_jar_leaves_dest_unchanged_when_the_write_fails():
    for target, name in ((m.os, "replace"), (m.tempfile, "mkstemp")):
        real = getattr(target, name)
        setattr(target, name, _failing(OSError))
        try:
            with tempfile.TemporaryDirectory() as d:
                raw = os.path.join(d, "raw.txt")
                with open(raw, "w", encoding="utf-8") as fh:
                    fh.write(BROWSER_JAR)
                out = _jar(d, "OLD JAR\n")
                try:
                    result = m.filter_jar(raw, "youtube", dest=out)
                except OSError as exc:
                    raise AssertionError(f"{name} failure escaped filter_jar: {exc}") from exc
                assert result is None, name
                with open(out, encoding="utf-8") as fh:
                    assert fh.read() == "OLD JAR\n", name
                assert sorted(os.listdir(d)) == ["raw.txt", "yt-cookies.txt"], os.listdir(d)
        finally:
            setattr(target, name, real)


def t_filter_jar_writes_through_a_symlinked_dest():
    if os.name != "posix":
        return
    with tempfile.TemporaryDirectory() as d:
        real_dir = os.path.join(d, "shared"); os.mkdir(real_dir)
        target = _jar(real_dir, "OLD JAR\n")
        link = os.path.join(d, "yt-cookies.txt")
        os.symlink(target, link)
        raw = os.path.join(d, "raw.txt")
        with open(raw, "w", encoding="utf-8") as fh:
            fh.write(BROWSER_JAR)
        assert m.filter_jar(raw, "youtube", dest=link) == 8
        assert os.path.islink(link)
        with open(target, encoding="utf-8") as fh:
            assert _names(fh.read()) == ["LOGIN_INFO", "SAPISID", "VISITOR"]


def t_private_export_path_is_an_owner_only_dir_removed_after():
    with tempfile.TemporaryDirectory() as d:
        out = os.path.join(d, "yt-cookies.txt")
        with m.private_export_path(out) as raw:
            tmpdir = os.path.dirname(raw)
            assert os.path.dirname(tmpdir) == os.path.realpath(d), tmpdir
            assert raw != out and os.path.basename(raw) == "yt-cookies.txt"
            if os.name == "posix":
                assert os.stat(tmpdir).st_mode & 0o777 == 0o700
            with open(raw, "w", encoding="utf-8") as fh:
                fh.write(BROWSER_JAR)
        assert not os.path.exists(tmpdir) and os.listdir(d) == []



def t_filter_drops_a_comment_line_with_a_control_character():
    # yt-dlp reads a lone "\r" as a line break, so a comment carrying one would
    # still hand it a cookie line.
    jar = "# note\tA\r.github.com\tTRUE\t/\tTRUE\t0\tgh_sess\tSECRET\n# Netscape HTTP Cookie File\n"
    assert m.filter_jar_text(jar, "youtube") == ("# Netscape HTTP Cookie File\n", 1)


def _stale_dir(parent, name, age_s):
    path = os.path.join(parent, name); os.mkdir(path)
    with open(os.path.join(path, "yt-cookies.txt"), "w", encoding="utf-8") as fh:
        fh.write(BROWSER_JAR)
    old = time.time() - age_s
    os.utime(path, (old, old))
    return path


def t_private_export_path_sweeps_only_old_leftover_exports():
    with tempfile.TemporaryDirectory() as d:
        stale = _stale_dir(d, ".cookie-export-killed", 3600)
        fresh = _stale_dir(d, ".cookie-export-running", 5)      # a concurrent export
        other = _stale_dir(d, "graphics", 3600)
        warnings = []
        with m.private_export_path(os.path.join(d, "yt-cookies.txt"), warn=warnings.append):
            pass
        assert not os.path.exists(stale)
        assert os.path.isdir(fresh) and os.path.isdir(other)
        assert warnings == [], warnings


def t_private_export_path_warns_when_a_dir_stays():
    with tempfile.TemporaryDirectory() as d:
        stale = _stale_dir(d, ".cookie-export-killed", 3600)
        real = m.shutil.rmtree
        m.shutil.rmtree = lambda *a, **k: None                   # e.g. a file held open
        warnings = []
        try:
            with m.private_export_path(os.path.join(d, "yt-cookies.txt"),
                                       warn=warnings.append) as raw:
                own = os.path.dirname(raw)
        finally:
            m.shutil.rmtree = real
        assert len(warnings) == 2, warnings
        # Basenames: the warning carries the realpath, which differs from the temp
        # dir's spelling on macOS (/private/var) and Windows (8.3 short names).
        assert warnings[0].endswith(os.path.basename(stale)), warnings
        assert warnings[1].endswith(os.path.basename(own)), warnings


def t_the_export_stamp_survives_a_yt_dlp_rewrite_of_the_jar():
    # yt-dlp --cookies writes the jar back on every resolve, so the jar's own mtime
    # measures the last resolve, not the last export. The stamp is a separate file
    # nothing but the export touches.
    with tempfile.TemporaryDirectory() as d:
        jar = os.path.join(d, "yt-cookies.txt")
        open(jar, "w", encoding="utf-8").close()
        assert m.export_age_h(jar) is None, "no stamp yet: the age is unknown, not zero"

        m.record_export(jar, now=1000.0)
        assert m.export_age_h(jar, now=1000.0 + 3 * 3600) == 3.0

        os.utime(jar, (2000.0, 2000.0))          # a resolve rewrites the jar
        assert m.export_age_h(jar, now=1000.0 + 3 * 3600) == 3.0, (
            "the rewritten jar must not reset the export age")


def t_a_damaged_or_missing_export_stamp_reads_as_unknown():
    # Never "fresh": an unreadable stamp must not be read as an export just now.
    with tempfile.TemporaryDirectory() as d:
        jar = os.path.join(d, "yt-cookies.txt")
        open(jar, "w", encoding="utf-8").close()
        with open(m.export_stamp_path(jar), "w", encoding="utf-8") as fh:
            fh.write("not a number")
        assert m.export_age_h(jar) is None
        assert m.export_age_h(None) is None


def t_recording_an_export_never_raises_when_the_stamp_cannot_be_written():
    # The export itself must not fail over its own bookkeeping.
    with tempfile.TemporaryDirectory() as d:
        jar = os.path.join(d, "sub", "yt-cookies.txt")   # the directory does not exist
        assert m.record_export(jar) is False


if __name__ == "__main__":
    for name, fn in sorted(globals().items()):
        if name.startswith("t_") and callable(fn):
            fn(); print("ok", name)
    print("ALL PASS")
