#!/usr/bin/env python3
"""Stdlib unit checks for cookie_jar.py (#615). Run: python3 tests/test_cookie_jar.py"""
import importlib.util, os, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
spec = importlib.util.spec_from_file_location(
    "cookie_jar", os.path.join(ROOT, "src", "scripts", "cookie_jar.py"))
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)

# The anonymous jar from the 2026-09-19 incident: three cookies, no login.
ANON_JAR = ("# Netscape HTTP Cookie File\n"
            ".youtube.com\tTRUE\t/\tTRUE\t0\t__Secure-YNID\tv\n"
            ".youtube.com\tTRUE\t/\tFALSE\t0\tPREF\tf6=40000000\n"
            ".youtube.com\tTRUE\t/\tTRUE\t0\tSOCS\tCAI\n")
LOGGED_IN_JAR = ANON_JAR + ".youtube.com\tTRUE\t/\tTRUE\t0\tLOGIN_INFO\tAFm\n"


def _jar(d, text):
    p = os.path.join(d, "yt-cookies.txt")
    with open(p, "w", encoding="utf-8") as fh:
        fh.write(text)
    return p


def t_text_has_login_needs_a_marker():
    assert m.text_has_login(ANON_JAR) is False
    assert m.text_has_login(LOGGED_IN_JAR) is True
    for marker in m.COOKIE_MARKERS:
        assert m.text_has_login(f".youtube.com\tTRUE\t/\tTRUE\t0\t{marker}\tv\n"), marker
    assert m.text_has_login("") is False and m.text_has_login(None) is False


def t_jar_has_login_reads_the_file():
    with tempfile.TemporaryDirectory() as d:
        assert m.jar_has_login(_jar(d, ANON_JAR)) is False
        assert m.jar_has_login(_jar(d, LOGGED_IN_JAR)) is True


def t_jar_has_login_is_unknown_without_a_jar():
    # No jar is "unknown", not "logged out": the relay must not blame a login it
    # never had a file for.
    assert m.jar_has_login(None) is None
    assert m.jar_has_login("") is None
    with tempfile.TemporaryDirectory() as d:
        assert m.jar_has_login(os.path.join(d, "nope.txt")) is None
        assert m.jar_has_login(d) is None            # a directory: unreadable as a jar


def t_hint_names_the_command():
    assert "racecast cookies <browser>" in m.LOGGED_OUT_HINT


# A browser export as yt-dlp writes it (#616): the whole profile, not one site.
BROWSER_JAR = ("# Netscape HTTP Cookie File\n"
               "# This file is generated by yt-dlp.  Do not edit.\n"
               "\n"
               ".youtube.com\tTRUE\t/\tTRUE\t0\tSAPISID\tyt\n"
               "#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t0\tLOGIN_INFO\tyt\n"
               "www.youtube.com\tFALSE\t/\tTRUE\t0\tVISITOR\tyt\n"
               ".google.com\tTRUE\t/\tTRUE\t0\tSID\tgoogle\n"
               "#HttpOnly_accounts.google.com\tFALSE\t/\tTRUE\t0\tLSID\tgoogle\n"
               ".github.com\tTRUE\t/\tTRUE\t0\tlogged_in\tgithub\n"
               ".twitch.tv\tTRUE\t/\tTRUE\t0\tauth-token\ttwitch\n"
               "id.twitch.tv\tFALSE\t/\tTRUE\t0\tlogin\ttwitch\n"
               ".notyoutube.com\tTRUE\t/\tTRUE\t0\tlook\talike\n"
               "youtube.com.evil.example\tFALSE\t/\tTRUE\t0\tlook\talike\n"
               "broken line without tabs\n")


def _names(text):
    return sorted(line.split("\t")[5] for line in text.splitlines()
                  if line.count("\t") == 6)


def t_filter_keeps_only_youtube_cookies():
    kept, dropped = m.filter_jar_text(BROWSER_JAR, "youtube")
    # .google.com is left out on purpose: requests to youtube.com never carry it,
    # and a live resolve with the youtube.com cookies alone was measured to work.
    assert _names(kept) == ["LOGIN_INFO", "SAPISID", "VISITOR"], _names(kept)
    assert dropped == 8, dropped
    assert kept.startswith("# Netscape HTTP Cookie File\n# This file is generated")
    assert m.text_has_login(kept) is True


def t_filter_keeps_only_twitch_cookies():
    kept, dropped = m.filter_jar_text(BROWSER_JAR, "twitch")
    assert _names(kept) == ["auth-token", "login"], _names(kept)
    assert dropped == 9, dropped


def t_filter_drops_lookalike_domains():
    kept, _ = m.filter_jar_text(BROWSER_JAR, "youtube")
    assert "alike" not in kept and "evil" not in kept and "github" not in kept
    assert "broken line" not in kept


def t_filter_rejects_an_unknown_platform():
    try:
        m.filter_jar_text(BROWSER_JAR, "vimeo")
    except ValueError as exc:
        assert "vimeo" in str(exc)
    else:
        raise AssertionError("an unknown platform must not keep everything")


def t_filter_jar_rewrites_the_file_owner_only():
    with tempfile.TemporaryDirectory() as d:
        p = _jar(d, BROWSER_JAR)
        assert m.filter_jar(p, "youtube") == 8
        with open(p, encoding="utf-8") as fh:
            assert _names(fh.read()) == ["LOGIN_INFO", "SAPISID", "VISITOR"]
        if os.name == "posix":
            assert os.stat(p).st_mode & 0o777 == 0o600, oct(os.stat(p).st_mode)
        assert os.listdir(d) == ["yt-cookies.txt"], os.listdir(d)   # no temp file left
        assert m.filter_jar(p, "youtube") == 0                      # idempotent


def t_filter_jar_is_none_without_a_jar():
    with tempfile.TemporaryDirectory() as d:
        assert m.filter_jar(os.path.join(d, "nope.txt"), "youtube") is None
        assert m.filter_jar(None, "youtube") is None


if __name__ == "__main__":
    for name, fn in sorted(globals().items()):
        if name.startswith("t_") and callable(fn):
            fn(); print("ok", name)
    print("ALL PASS")
