#!/usr/bin/env python3
"""Replace absolute asset paths in an OBS collection with the __RACECAST_GRAPHICS__ token.

Recognized assets are every image_source 'file' path: the broadcast graphics live in
runtime/graphics and are tokenized to __RACECAST_GRAPHICS__/<basename>. Path matching is
separator-agnostic. Idempotent, so already-tokenized paths are left alone.

Usage: tokenize-obs.py IN [OUT]
"""
import argparse, json, os, re

TOKEN = "__RACECAST_GRAPHICS__"
MEDIA_TOKEN = "__RACECAST_MEDIA__"
SHEET_TOKEN = "__RACECAST_SHEET__"
# Any /spreadsheets/d/<id>/. The {20,} length guard skips the short token itself.
SHEET_RE = re.compile(r"(/spreadsheets/d/)[A-Za-z0-9_-]{20,}(/)")

# Fold any platform variant of the Discord audio source back to the committed
# macOS form, so round-trips from Mac and Windows yield the same template.
# setup-assets' localize_discord_audio is the other end; keep the two in sync.
DISCORD_AUDIO_UUID = "0085d4f3-bf43-4aef-9fe4-28cfd3270c7d"
DISCORD_AUDIO_CANONICAL = ("sck_audio_capture",
                           {"type": 1, "application": "com.hnc.Discord"})


# The canonical scene-collection name in the committed source. Mirrors
# obs_ws.EXPECTED_SCENE_COLLECTION and src/obs/GT_Racing_Endurance.json's "name";
# rename all three together. Folding an export back resets the name so a
# per-league name, written by setup-assets, never lands in git.
CANONICAL_COLLECTION_NAME = "GT Racing Endurance"


def canonicalize_name(d):
    """Reset the collection's display name to the canonical source name."""
    d["name"] = CANONICAL_COLLECTION_NAME
    return d


def canonicalize_discord_audio(d):
    """True iff a non-canonical Discord audio source was rewritten."""
    src_id, settings = DISCORD_AUDIO_CANONICAL
    for s in d.get("sources", []):
        if s.get("uuid") == DISCORD_AUDIO_UUID and s.get("id") != src_id:
            s["id"] = src_id
            s["versioned_id"] = src_id
            s["settings"] = dict(settings)
            return True
    return False


# The endurance commentary mic, folded back to its committed macOS form. An export
# from a producer machine carries its real device id, and mid-stint the mic open;
# the template ships the token and the mic closed. (#593)
MIC_SOURCE = "Commentary Mic Device"
MIC_CANONICAL = ("coreaudio_input_capture", {"device_id": "__RACECAST_MIC__"})


def canonicalize_commentary_mic(d):
    """True iff the commentary mic leaf was rewritten to its committed form.
    Endurance only, meaning a collection with a Stint scene: the solo collections
    ship the mic hot and are regenerated by derive-solo-templates.py, never
    tokenized."""
    if not any(s.get("name") == "Stint" and s.get("id") == "scene" for s in d.get("sources", [])):
        return False
    src_id, settings = MIC_CANONICAL
    for s in d.get("sources", []):
        if s.get("name") != MIC_SOURCE:
            continue
        if s.get("id") == src_id and s.get("settings") == settings and s.get("muted") is True:
            return False
        s["id"] = s["versioned_id"] = src_id
        s["settings"] = dict(settings)
        s["muted"] = True
        return True
    return False


def base(path):
    """basename that splits on both / and \\, regardless of host OS."""
    return os.path.basename(path.replace("\\", "/"))


def tokenize_sheets(obj, counter):
    """Recursively replace any Google-Sheet ID in a URL with __RACECAST_SHEET__."""
    if isinstance(obj, dict):
        return {k: tokenize_sheets(v, counter) for k, v in obj.items()}
    if isinstance(obj, list):
        return [tokenize_sheets(v, counter) for v in obj]
    if isinstance(obj, str):
        new, c = SHEET_RE.subn(rf"\g<1>{SHEET_TOKEN}\g<2>", obj)
        counter[0] += c
        return new
    return obj


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src")
    ap.add_argument("out", nargs="?", default=None)
    a = ap.parse_args()
    out = a.out or a.src

    with open(a.src, encoding="utf-8") as fh:
        d = json.load(fh)
    n = 0
    for s in d.get("sources", []):
        if s.get("id") != "image_source":
            continue
        st = s.get("settings") or {}
        f = st.get("file")
        if isinstance(f, str) and f and not f.startswith("__RACECAST_"):
            st["file"] = f"{TOKEN}/{base(f)}"
            n += 1
    # Intro/Outro clips are ffmpeg_source local_file paths -> __RACECAST_MEDIA__.
    # Feed A/B/POV are ffmpeg_source too but use a loopback `input` URL with no
    # local_file, so they are left untouched. setup-assets.py replaces the token
    # with the runtime media dir; without this a re-export leaks an absolute path.
    m = 0
    for s in d.get("sources", []):
        if s.get("id") != "ffmpeg_source":
            continue
        st = s.get("settings") or {}
        f = st.get("local_file")
        if isinstance(f, str) and f and not f.startswith("__RACECAST_"):
            st["local_file"] = f"{MEDIA_TOKEN}/{base(f)}"
            m += 1
    sheet_count = [0]
    d = tokenize_sheets(d, sheet_count)
    if canonicalize_discord_audio(d):
        print("Discord audio source folded back to the canonical macOS form.")
    if canonicalize_commentary_mic(d):
        print("Commentary mic folded back to the token form (muted).")
    canonicalize_name(d)
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(d, fh, ensure_ascii=False, indent=4)
    print(f"tokenized {n} graphics + {m} media path(s) + "
          f"{sheet_count[0]} sheet URL(s) -> {out}")


if __name__ == "__main__":
    main()
